# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        container_name: laravel.test
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-15901}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        labels:
            - traefik.enable=true
            - traefik.http.routers.api1591.rule=Host(`api.specter1591.com`)
            - traefik.http.services.api1591.loadbalancer.server.port=80
        # network_mode: host
        networks:
            - network
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        container_name: ${DB_HOST:-postgres}
        image: postgres:latest
        pull_policy: always
        environment:
            - POSTGRES_USER=${DB_USERNAME:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
            - POSTGRES_DB=${DB_DATABASE:-postgres}
        volumes:
          - ./dev/postgres:/var/lib/postgresql/data
        ports:
            - 59432:5432
        networks:
            - network
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        pull_policy: always
        ports:
            - 59050:80
            - 59051:443
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@specter1591.com
            - PGADMIN_DEFAULT_PASSWORD=admin
    redis:
        container_name: redis
        image: redis:latest
        pull_policy: always
        volumes:
          - ./dev/redis:/data
        networks:
            - network
    soketi:
        container_name: soketi
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        pull_policy: always
        environment:
            - DEBUG='1'
            - METRICS_SERVER_PORT='9601'
            - DEFAULT_APP_ID = ${PUSHER_APP_ID:-app-id}
            - DEFAULT_APP_KEY = ${PUSHER_APP_KEY:-app-key}
            - DEFAULT_APP_SECRET = ${PUSHER_APP_SECRET:-app-secret}
        ports:
            - ${PUSHER_PORT:-6001}:6001
            - ${SOCKETI_METRICS_SERVERPORT:-9601}:9601
        networks:
            - network
    chrome:
        image: selenium/node-chrome:latest
        container_name: selenium-chrome
        restart: unless-stopped
        pull_policy: always
        shm_size: 2gb
        depends_on:
        - selenium-hub
        environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_NODE_MAX_SESSIONS=100
        - SE_NODE_OVERRIDE_MAX_SESSIONS=true
        - SE_NODE_SESSION_TIMEOUT=15
        - SE_START_XVFB=false

    selenium-hub:
        image: selenium/hub:latest
        restart: unless-stopped
        pull_policy: always
        container_name: selenium
        ports:
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"
networks:
    network:
        name: network
