apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- keda.yaml
- service.yaml
- secret.yaml
namespace: specter1591-api
images:
- name: registry.specter1591.com/specter1591/api/master
  newTag: b61ce48d65c9ab017d8bb8730679c65c4934e770
